export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL='AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADD_TODO_START = 'ADD_TODO_START';
export const ADD_TODO_SUCCESS='ADD_TODO_SUCCESS';
export const ADD_TODO_FAIL='ADD_TODO_FAIL';

export const FETCH_TODOS_START='FETCH_TODOS_START';
export const FETCH_TODOS_SUCCESS='FETCH_TODOS_SUCCESS';
export const FETCH_TODO_FAIL='FETCH_TODO_FAIL';

export const TOGGLE_TODO ='TOGGLE_TODO';

export const START_DELETE='START_DELETE';
export const DELETE_TODO='DELETE_TODO';
export const DELETE_FAIL='DELETE_FAIL';


